services:
  dart_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dart_server
    ports:
      - "5006:5000"
      - "5050:5050"
    environment:
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - PORT=${PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - WS_PORT=${WS_PORT}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_USERPASS=${DB_USERPASS}
      - ADMIN=${ADMIN}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
    volumes:
      - .:/app
    networks:
      - dart_network
    restart: unless-stopped

networks:
  dart_network:
