export enum DatabaseAvailableLabels {
  USER = "USER",
  SECURITY_DEVICE = "SECURITY_DEVICE",
  POST = "POST",
  API_LOG = "API_LOG",
  COMMENT = "COMMENT",
  MESSAGE = "MESSAGE",
  LIKE = "LIKE"
}

export enum DatabaseAvailableRelations {
  DEVICE = "DEVICE",
  USER_POST = "USER_POST",
  FRIEND = "FRIEND",
  USER_COMMENT = "USER_COMMENT",
  POST_COMMENT = "POST_COMMENT",
  USER_MESSAGE = "USER_MESSAGE",
  POST_LIKE = "POST_LIKE",
  COMMENT_LIKE = "COMMENT_LIKE",
  USER_LIKE = "USER_LIKE",
}
