openapi: 3.0.3
info:
  title: Swagger Dart - OpenAPI 3.0
  description: |-
    DART Social network API
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:5000/api/v1
    description: Development server
tags:
  - name: Auth
    description: Everything about Login page
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
 
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login in Dart
      description: Login in Dart
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserBody"
      responses:
        '200':
          description: Successful login operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: Password incorrect 
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: User not found
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /auth/registration:
    post:
      tags:
        - Auth
      summary: Registration in Dart
      description: Registration in Dart
      operationId: registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegBody"
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                 message: 
                  type: string
                  example: 'Registration success'
        '400':
          description: Registration error 
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /auth/me/{user_id}:
    get:
      tags:
        - Auth
      summary: Initialization user in the Dart
      description: Initialization user in the Dart
      operationId: getMe
      parameters: 
        - name: user_id
          in: path
          required: true
          description: user ID
          schema: 
            type: string
          example: c2c4b3d0-1a45-11ed-9c43-3ff339ee199d
      responses:
        '200':
          description: Successful initialization
          content:
            application/json:
              schema:
                type: object
                properties:
                  email: 
                    type: string
                    example: test@example.com
                  role:
                    type: string
                    example: User
                  user_id:
                    type: string
                    example: c2c4b3d0-1a45-11ed-9c43-3ff339ee199d
        '403':
          description: Unauthorized 
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"



components:
  schemas: 
    UserBody:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: test@example.com
        password: 
          type: string
          example: demo
    User:
      type: object
      properties:
        user_id:
          type: string
          example: c2c4b3d0-1a45-11ed-9c43-3ff339ee199d
        email: 
          type: string
          example: demo@example.com
        roles: 
          type: array
          items: 
            $ref: '#/components/schemas/Role'
        token: 
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ .eyJpZCI6IjYyZjUxODM2YjBjYzk1MzU1ODgzYWU5YSIsInJvbGVzIjpbIlVzZXIiXSwiaWF0IjoxNjYwMzA2OTM5LCJleHAiOjE2NjAzOTMzMzl9.iAWUoVRj5uxELIbNzcNdhEMb8YXyIXflTalZfIUCNwo
    UserRegBody: 
      type: object
      required:
        - email
        - password
      properties:
        email: 
          type: string
          example: demo@example.com
        password: 
          type: string
          example: demo
    Role:
     type: string
     example: user
      
    Error:
      type: object
      properties:
        message:
          type: string
          example: Error message
      required: 
        - message
   
  
  
  
  